# Generated by Django 3.2.23 on 2023-12-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_api', '0003_alter_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzedimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
